_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 10
learning_rate:
    value: 0.1
optimizer:
    value: NAdam
